name: ora-free-bug
on:
  push:
    paths:
      - '**/ora-free-bug.yml'
jobs:
  test-oracle-free:
    strategy:
      fail-fast: false
      matrix:
        tag: [23.6.0.0-lite, latest-lite]
        runtime: [docker, podman]
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - run: >-
          ${{ matrix.runtime }} run -d --name oracle-db
          container-registry.oracle.com/database/free:${{ matrix.tag }}
      - run: |
          while ! { ${{ matrix.runtime }} logs oracle-db | grep -q "^The following output is now a tail of the alert\.log:$"; }; do
            sleep 5
          done
          sleep 5
      - run: |
          echo "::group::Logs"
          ${{ matrix.runtime }} logs oracle-db
          echo "::endgroup::"
          status=$(${{ matrix.runtime }} inspect -f "{{.State.Status}}" oracle-db)
          [[ $status = "running" ]] && exit 0 || exit 1
